name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          source venv/bin/activate
          pyinstaller --noconfirm vial.spec

      - uses: actions/upload-artifact@v4
        with:
          name: vial-macos
          path: dist/Vial.app

  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0-dev libudev-dev

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          source venv/bin/activate
          pyinstaller --noconfirm vial.spec

      - uses: actions/upload-artifact@v4
        with:
          name: vial-linux
          path: dist/Vial

  build-windows:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: powershell
        run: |
          python -m venv venv
          . .\venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        shell: powershell
        run: |
          . .\venv\Scripts\Activate.ps1
          pyinstaller --noconfirm vial.spec

      - uses: actions/upload-artifact@v4
        with:
          name: vial-windows
          path: dist/Vial
